// FILE GENERATED BY: flutterfire configure
// OR manually fill in the values from your Firebase project settings.
//
// 1. Go to https://console.firebase.google.com
// 2. Open your project → Project Settings → Your apps
// 3. Add an Android app (package name: com.example.allowlist_browser)
// 4. Download google-services.json → place in android/app/
// 5. Copy the values below from the Firebase console (Web app config or Android config)
//
// TIP: Run `flutterfire configure` from your project root to auto-generate this file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── REPLACE THESE WITH YOUR REAL VALUES ────────────────────────────────────
  // Find them at: Firebase Console → Project Settings → Your apps → SDK setup

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',           // e.g. 1:123456789:android:abcdef
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',               // e.g. 1:123456789:ios:abcdef
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.allowlistBrowser',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
  // ─────────────────────────────────────────────────────────────────────────────
}
